### ISSUE TITLE
API

### ISSUE THREAD

**Issue by vdigregorio** [vdigregorio/encyc-lyric-pedia#1]
I cant get my API to print out the information im asking for:
I tried to fix the URL, because i thought maybe that was it, i changed my function names and implemented them in services js folder, and i googled it...... I also asked my classmates for help!

**Comment by vdigregorio** [comment]
@gittheking
@jasonseminara
@trevorpreston
@rapala61
@Irwintsay

**Comment by trevorpreston** [comment]
Taken care of.

@vdigregorio please close this issue when you get a minute!
