### ISSUE TITLE
models

### ISSUE THREAD

**Issue by vdigregorio** [vdigregorio/encyc-lyric-pedia#2]
I implemented the user authentication, its working but now my models pages aren't rendering, im sure its something in the routes but i cannot identify. I tried changing routes that i believed were part of the ejs files but the changes didn't do anything, I researched different methods to work with this type of problem on google and didn't get anything useful and then I asked a classmate for an extra eye on this problem.

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@Irwintsay

**Comment by vdigregorio** [comment]
@trevorpreston

**Comment by vdigregorio** [comment]
@trevorpreston

**Comment by vdigregorio** [comment]
@trevorpreston

**Comment by irwintsay** [comment]
Issue solved, please close!
