### ISSUE TITLE
STYLESHEET

### ISSUE THREAD

**Issue by vdigregorio** [vdigregorio/encyc-lyric-pedia#4]
I am unable to connect my stylesheets to my ejs! I changed the app.use(express.static('public')); to app.use(express.static(path.join(__dirname, 'public'))); and changed the href to "/css/style.css", looked at other projects to see how they were connecting their stylesheets and tried several different things. Everything seems to be correct but it doesnt work!

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@Irwintsay

**Comment by gittheking** [comment]
@vdigregorio, `href="/css/style.css"` won't work because you don't have a `css` directory in your `public`. The path to your stylesheets should just be `style.css`

**Comment by vdigregorio** [comment]
thanks!
